openapi: 3.0.0
info:
  version: '2017-10-01'
  x-release: v4
  title: 'Amazon WorkMail #X Amz Target=WorkMailService.AssociateDelegateToResource #X Amz Target=WorkMailService.AssociateDelegateToResource #X Amz Target=WorkMailService.ListMailboxPermissions API'
  description: <p>WorkMail is a secure, managed business email and calendaring service with support for existing desktop and mobile email clients. You can access your email, contacts, and calendars using Microsoft Outlook, your browser, or other native iOS and Android email applications. You can integrate WorkMail with your existing corporate directory and control both the keys that encrypt your data and the location in which your data is stored.</p> <p>The WorkMail API is designed for the following scenarios:</p> <ul> <li> <p>Listing and describing organizations</p> </li> </ul> <ul> <li> <p>Managing users</p> </li> </ul> <ul> <li> <p>Managing groups</p> </li> </ul> <ul> <li> <p>Managing resources</p> </li> </ul> <p>All WorkMail API operations are Amazon-authenticated and certificate-signed. They not only require the use of the AWS SDK, but also allow for the exclusive use of AWS Identity and Access Management users and roles to help facilitate access, trust, and permission policies. By creating a role and allowing an IAM user to access the WorkMail site, the IAM user gains full administrative visibility into the entire WorkMail organization (or as set in the IAM policy). This includes, but is not limited to, the ability to create, update, and delete users, groups, and resources. This allows developers to perform the scenarios listed above, as well as give users the ability to grant access on a selective basis using the IAM model.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: workmail
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/workmail-2017-10-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://workmail.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon WorkMail multi-region endpoint
- url: https://workmail.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon WorkMail multi-region endpoint
- url: http://workmail.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon WorkMail endpoint for China (Beijing) and China (Ningxia)
- url: https://workmail.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon WorkMail endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=WorkMailService.ListMailboxPermissions'
paths:
  /#X-Amz-Target=WorkMailService.ListMailboxPermissions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListMailboxPermissions
      description: Lists the mailbox permissions associated with a user, group, or resource mailbox.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMailboxPermissionsResponse'
        '480':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
        '481':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '482':
          description: OrganizationNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationNotFoundException'
        '483':
          description: OrganizationStateException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationStateException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListMailboxPermissionsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - WorkMailService.ListMailboxPermissions
      summary: Amazon WorkMail List Mailbox Permissions
      tags:
      - '#X Amz Target=WorkMailService.ListMailboxPermissions'
components:
  schemas:
    Permission:
      type: object
      required:
      - GranteeId
      - GranteeType
      - PermissionValues
      properties:
        GranteeId:
          allOf:
          - $ref: '#/components/schemas/WorkMailIdentifier'
          - description: The identifier of the user, group, or resource to which the permissions are granted.
        GranteeType:
          allOf:
          - $ref: '#/components/schemas/MemberType'
          - description: The type of user, group, or resource referred to in GranteeId.
        PermissionValues:
          allOf:
          - $ref: '#/components/schemas/PermissionValues'
          - description: The permissions granted to the grantee. SEND_AS allows the grantee to send email as the owner of the mailbox (the grantee is not mentioned on these emails). SEND_ON_BEHALF allows the grantee to send email on behalf of the owner of the mailbox (the grantee is not mentioned as the physical sender of these emails). FULL_ACCESS allows the grantee full access to the mailbox, irrespective of other folder-level permissions set on the mailbox.
      description: Permission granted to a user, group, or resource to access a certain aspect of another user, group, or resource mailbox.
    OrganizationStateException: {}
    OrganizationId:
      type: string
      pattern: ^m-[0-9a-f]{32}$
      minLength: 34
      maxLength: 34
    InvalidParameterException: {}
    PermissionType:
      type: string
      enum:
      - FULL_ACCESS
      - SEND_AS
      - SEND_ON_BEHALF
    OrganizationNotFoundException: {}
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      pattern: '[\S\s]*|[a-zA-Z0-9/+=]{1,1024}'
      minLength: 1
      maxLength: 1024
    ListMailboxPermissionsResponse:
      type: object
      properties:
        Permissions:
          allOf:
          - $ref: '#/components/schemas/Permissions'
          - description: One page of the user, group, or resource mailbox permissions.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The token to use to retrieve the next page of results. The value is "null" when there are no more results to return.
    WorkMailIdentifier:
      type: string
      minLength: 12
      maxLength: 256
    EntityNotFoundException: {}
    PermissionValues:
      type: array
      items:
        $ref: '#/components/schemas/PermissionType'
    MemberType:
      type: string
      enum:
      - GROUP
      - USER
    ListMailboxPermissionsRequest:
      type: object
      required:
      - OrganizationId
      - EntityId
      title: ListMailboxPermissionsRequest
      properties:
        OrganizationId:
          allOf:
          - $ref: '#/components/schemas/OrganizationId'
          - description: The identifier of the organization under which the user, group, or resource exists.
        EntityId:
          allOf:
          - $ref: '#/components/schemas/WorkMailIdentifier'
          - description: The identifier of the user, group, or resource for which to list mailbox permissions.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The token to use to retrieve the next page of results. The first call does not contain any tokens.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/MaxResults'
          - description: The maximum number of results to return in a single call.
    Permissions:
      type: array
      items:
        $ref: '#/components/schemas/Permission'
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/workmail/
x-hasEquivalentPaths: true
